<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contract extends Model
{
    use HasFactory;

    protected $guarded=[];

    public function contractProducts(){
        return $this->hasMany(ContractProduct::class, "contract_id", "contractId");
    }

    public function contractParts(){
        return $this->hasMany(ContractPart::class, "contract_id", "contractId");
    }

    public function contractPartners(){
        return $this->hasMany(ContractPartner::class, "contract_id", "contractId");
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function ($contract){
            $contract->contractParts()->delete();
            $contract->contractProducts()->delete();
            $contract->contractPartners()->delete();
        });
    }
}
